### ISSUE TITLE
Hide Packages & Releases

### ISSUE THREAD

**Issue by verma-kunal** [annshiv/python-projects#1]
Suggested to hide packages and releases, if not being used in the repo/project !!

Screenshot:
![Screenshot 2021-06-06 at 12 21 45 AM](https://user-images.githubusercontent.com/72245772/120902299-2e8a3600-c65d-11eb-831a-93efa83de757.png)

**Comment by annshiv** [comment]
Okay. Thanks for your suggestions. I will hide.
